config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :decks

  resources :games

  get "games/:id/pick_up/:card_id", to: "games#pick_up"

  get "games/:id", to: "games#shuffle"

  get "games/:id/put_back/:card_id", to: "games#put_back"

  resources :hands

  resources :cards

  root to: "games#index"

end

app/models/hand.rb
class Hand < ActiveRecord::Base
end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
  before_action :set_hand, only: [:show, :edit, :update, :destroy]

  # GET /hands
  # GET /hands.json
  def index
    @hands = Hand.all
  end

  # GET /hands/1
  # GET /hands/1.json
  def show
  end

  # GET /hands/new
  def new
    @hand = Hand.new
  end

  # GET /hands/1/edit
  def edit
  end

  # POST /hands
  # POST /hands.json
  def create
    @hand = Hand.new(hand_params)

    respond_to do |format|
      if @hand.save
        format.html { redirect_to @hand, notice: 'Hand was successfully created.' }
        format.json { render :show, status: :created, location: @hand }
      else
        format.html { render :new }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hands/1
  # PATCH/PUT /hands/1.json
  def update
    respond_to do |format|
      if @hand.update(hand_params)
        format.html { redirect_to @hand, notice: 'Hand was successfully updated.' }
        format.json { render :show, status: :ok, location: @hand }
      else
        format.html { render :edit }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hands/1
  # DELETE /hands/1.json
  def destroy
    @hand.destroy
    respond_to do |format|
      format.html { redirect_to hands_url, notice: 'Hand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hand
      @hand = Hand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hand_params
      params.require(:hand).permit(:user_id, :card_id, :game_id)
    end
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/views/hands/_form.html.erb
<%= form_for(@hand, html:{ class: "form-horizontal"}) do |f| %>
  <% if @hand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hand.errors.count, "error") %> prohibited this hand from being saved:</h2>

      <ul>
      <% @hand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :card_id %><br>
    <%= f.number_field :card_id %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hands/edit.html.erb
<div class="col-sm-2"></div><div class="col-sm-10"><h1>Editing Hand</h1></div>

<%= render 'form' %>

<%= link_to 'Show', @hand %> |
<%= link_to 'Back', hands_path %>

app/views/hands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hands</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Card</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hands.each do |hand| %>
      <tr>
        <td><%= hand.user_id %></td>
        <td><%= hand.card_id %></td>
        <td><%= hand.game_id %></td>
        <td><%= link_to 'Show', hand %></td>
        <td><%= link_to 'Edit', edit_hand_path(hand) %></td>
        <td><%= link_to 'Destroy', hand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hand', new_hand_path,  class: "btn btn-primary" %>

app/views/hands/new.html.erb
<div class="col-sm-2"></div><div class="col-sm-10"><h1>New Hand</h1></div>

<%= render 'form' %>

<%= link_to 'Back', hands_path %>

app/views/hands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @hand.user_id %>
</p>

<p>
  <strong>Card:</strong>
  <%= @hand.card_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @hand.game_id %>
</p>
<%= link_to 'Edit', edit_hand_path(@hand) %> |
<%= link_to 'Back', hands_path %>