config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :decks

  resources :games

  get "games/:id/pick_up/:card_id", to: "games#pick_up"

  get "games/:id", to: "games#shuffle"

  get "games/:id/put_back/:card_id", to: "games#put_back"

  resources :hands

  resources :cards

  root to: "games#index"

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :deck
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    @card.deck_id = params[:deck_id]
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:deck_id, :name, :attr_one, :attr_two, :attr_three, :attr_four, :attr_five, :attr_six, :attr_description)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card, html:{ class: "form-horizontal"}) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :deck_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:deck_id, Deck.all, :id, :name, {}, class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attr_one, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :attr_one, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attr_two, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :attr_two, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attr_three, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :attr_three, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attr_four, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :attr_four, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attr_five, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :attr_five, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attr_six, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :attr_six, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :attr_description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :attr_description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-10">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="col-sm-2"></div><div class="col-sm-10"><h1>Editing Card</h1></div>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Attr one</th>
      <th>Attr two</th>
      <th>Attr three</th>
      <th>Attr four</th>
      <th>Attr five</th>
      <th>Attr six</th>
      <th>Attr description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.attr_one %></td>
        <td><%= card.attr_two %></td>
        <td><%= card.attr_three %></td>
        <td><%= card.attr_four %></td>
        <td><%= card.attr_five %></td>
        <td><%= card.attr_six %></td>
        <td><%= card.attr_description %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path, class: "btn btn-primary" %>

app/views/cards/new.html.erb
<div class="col-sm-2"></div><div class="col-sm-10"><h1>New Card</h1></div>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Attr one:</strong>
  <%= @card.attr_one %>
</p>

<p>
  <strong>Attr two:</strong>
  <%= @card.attr_two %>
</p>

<p>
  <strong>Attr three:</strong>
  <%= @card.attr_three %>
</p>

<p>
  <strong>Attr four:</strong>
  <%= @card.attr_four %>
</p>

<p>
  <strong>Attr five:</strong>
  <%= @card.attr_five %>
</p>

<p>
  <strong>Attr six:</strong>
  <%= @card.attr_six %>
</p>

<p>
  <strong>Attr description:</strong>
  <%= @card.attr_description %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>