config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :decks

  resources :games

  get "games/:id/pick_up/:card_id", to: "games#pick_up"

  get "games/:id", to: "games#shuffle"

  get "games/:id/put_back/:card_id", to: "games#put_back"

  resources :hands

  resources :cards

  root to: "games#index"

end

app/models/deck.rb
class Deck < ActiveRecord::Base
	has_many :cards
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name, :styling)
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck, html:{ class: "form-horizontal"}) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :styling, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :styling, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
    <%= f.submit "Save", class: "btn btn-primary" %>

    <% if @deck.id %>
      <%= link_to 'Show', @deck, class: "btn btn-default" %>
      <%= link_to 'Back', deck_path(@deck), class: "btn btn-default" %>
    <% else %>
      <%= link_to 'Back', decks_path, class: "btn btn-default" %>    
    <% end %>
    </div>
  </div>
<% end %>

app/views/decks/edit.html.erb
<div class="col-sm-2"></div><div class="col-sm-10"><h1>Editing Deck</h1></div>

<%= render 'form' %>

app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Decks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path, class: "btn btn-primary" %>

app/views/decks/new.html.erb
<div class="col-sm-2"></div><div class="col-sm-10"><h1>New Deck</h1></div>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deck.name %>
</p>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>
<%= link_to 'New Card',  "/cards/new?deck_id=#{@deck.id}" %>
<% @deck.cards.each do |card| %>
  <%= card.name %>
<% end %>